WebApp/Controllers/MeetRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using BLL;
using Common;
using System.Collections;

namespace WebApp.Controllers
{
    [Authorize(Roles="admin")]
    public class MeetRoomController : Controller
    {
        private IMeetService meetService = BLLContainer.Resolve<IMeetService>();
        private IExamineService examineService = BLLContainer.Resolve<IExamineService>();
        private IMeetMsgService meetMsgService = BLLContainer.Resolve<IMeetMsgService>();
        private IMeetRoomService meetRoomService = BLLContainer.Resolve<IMeetRoomService>();

        //
        // GET: /MeetRoom/
        public ActionResult Index(string searchString)
        {
            int pageSize = 5;
            int itemCount;
            if (!String.IsNullOrEmpty(searchString))
            {
                itemCount = meetRoomService.GetModels(p => p.Name.Contains(searchString) || p.Content.Contains(searchString)).Count();
            }
            else
            {
                itemCount = meetRoomService.GetModels(p => true).Count();
            }
            int pageCount = Convert.ToInt32(Math.Ceiling((double)itemCount / pageSize));
            //当前页码值
            int pageIndex = Request.Params["pageIndex"] == null ? 1 : int.Parse(Request.Params["pageIndex"]);
            pageIndex = pageIndex > pageCount ? pageCount : pageIndex;
            List<MeetRoom> meetRooms = null;
            if (itemCount != 0 && pageIndex != 0)
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    meetRooms = meetRoomService.GetModelsByPage(pageSize, pageIndex, true, a => a.Name, p => p.Name.Contains(searchString) || p.Content.Contains(searchString)).ToList();
                }
                else
                {
                    meetRooms = meetRoomService.GetModelsByPage(pageSize, pageIndex, true, a => a.Name, p => true).ToList();
                }
            }
            ViewData["meetRooms"] = meetRooms;
            ViewData["pageCount"] = pageCount;
            ViewData["pageIndex"] = pageIndex;
            ViewData["searchString"] = searchString;
            return View();
        }

        #region 会议室管理

        [Authorize(Roles="admin,apply")]
        public ActionResult TimeIsUsed()
        {
            string data = null;
            int id = int.Parse(Request.Params["id"]);
            string dateStr = Request.Params["time"].Split(' ')[0];
            DateTime dateTime = DateTime.Parse(Request.Params["time"]);
            if (dateTime == null)
            {
                return Content("输入时间格式有误");
            }
            MeetRoom meetRoom = meetRoomService.GetModels(p => p.MeetRoomId == id).FirstOrDefault();
            String[] dates = new String[0];
            if (meetRoom != null && !String.IsNullOrEmpty(meetRoom.UseTime))
            {
                dates = meetRoom.UseTime.Split('|');
            }
            foreach (String date in dates)
            {
                String[] startend = date.Split(',');
                String[] startStrArr = startend[1].Split(' ');
                String[] endStrArr = startend[2].Split(' ');
                String startStr = startStrArr[0].Replace("/", "-");
                String endStr = endStrArr[0].Replace("/", "-");
                if (DateTime.Parse(startStr).CompareTo(DateTime.Parse(dateStr))==0 || DateTime.Parse(endStr).CompareTo(DateTime.Parse(dateStr))==0)
                {
                    if (data != null)
                    {
                        data += "\n"+startStrArr[1] + "到" + endStrArr[1];
                    }
                    else
                    {
                        data += "今天有会议：" + startStrArr[1] + "到" + endStrArr[1];
                    }
                }
            }
            return Content(data);
        }

        public ActionResult GetUseTime()
        {
            string data = null;
            List<String> list = new List<String>();
            int id = int.Parse(Request.Params["id"]);
            MeetRoom meetRoom = meetRoomService.GetModels(p => p.MeetRoomId == id).FirstOrDefault();
            String[] dates = new String[0];
            if (meetRoom != null && !String.IsNullOrEmpty(meetRoom.UseTime))
            {
                dates = meetRoom.UseTime.Split('|');
            }
            foreach (String date in dates)
            {
                String[] startend = date.Split(',');
                String[] startStrArr = startend[1].Split(' ');
                String[] endStrArr = startend[2].Split(' ');
                String startStr = startStrArr[0].Replace("/", "-");
                String endStr = endStrArr[0].Replace("/", "-");
                String startDay = startStr.Split('-')[2];
                String endDay = startStr.Split('-')[2];
                //int startDay = int.Parse(startStr.Split('-')[2]);
                //int endDay = int.Parse(startStr.Split('-')[2]);
                if (!list.Contains(startDay))
                {
                    list.Add(startDay);
                }
                if (list.Contains(endDay))
                {
                    list.Add(endDay);
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);;
        }
        public ActionResult AddMeetRoom()
        {
            if (Request.Params["id"] != null)
            {
                int id = int.Parse(Request.Params["id"]);
                MeetRoom meetRoom = meetRoomService.GetModels(p => p.MeetRoomId == id).FirstOrDefault();
                ViewData["meetRoom"] = meetRoom;
                ViewData["Name"] = meetRoom.Name;
                ViewData["HoldPerson"] = meetRoom.HoldPerson;
                ViewData["Address"] = meetRoom.Address;
                ViewData["Describe"] = meetRoom.Describe;
                ViewData["Picture"] = meetRoom.Picture;
                ViewData["Status"] = meetRoom.Status;
                ViewData["MeetRoomId"] = meetRoom.MeetRoomId;
            }
            return View();
        }
       
        [ValidateInput(false)]
        public ActionResult Add(MeetRoom meetRoom)
        {
            if (meetRoom.MeetRoomId != 0)
            {

                //显示加载
                MeetRoom updateMeetRoom = meetRoomService.GetModels(p => p.MeetRoomId == meetRoom.MeetRoomId).FirstOrDefault();


                updateMeetRoom.Name = meetRoom.Name;
                updateMeetRoom.HoldPerson = meetRoom.HoldPerson;
                updateMeetRoom.Address = meetRoom.Address;
                updateMeetRoom.Describe = meetRoom.Describe;
                //updateMeetRoom.Picture = meetRoom.Picture;
                if (updateMeetRoom.Name != null && meetRoomService.Update(updateMeetRoom))
                {
                    return Content("ok");
                }
                else
                {
                    return Content("no");
                }
            }
            else
            {
                if (meetRoom.Name != null && meetRoomService.Add(meetRoom))
                {
                    return Content("ok");
                }
                else
                {
                    return Content("no");
                }
            }
        }

        public ActionResult Delete()
        {
            int id = int.Parse(Request["id"]);
            MeetRoom meetRoom = meetRoomService.GetModels(p => p.MeetRoomId == id).FirstOrDefault();
            if (meetRoomService.Delete(meetRoom))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        public ActionResult MeetRoomDetail()
        {
            int id = int.Parse(Request["id"]);
            MeetRoom meetRoom = meetRoomService.GetModels(p => p.MeetRoomId == id).FirstOrDefault();
            return Json(meetRoom, JsonRequestBehavior.AllowGet);
        }
        #endregion
	}
}

WebApp/Views/MeetRoom/AddMeetRoom.cshtml
@{
    Layout = null;
}
@using Microsoft.AspNet.Identity
@using System.Web.Security
@Styles.Render("~/Content/table")
@Styles.Render("~/Content/easyui")
@Scripts.Render("~/bundles/easyui")
@Scripts.Render("~/bundles/ajax")
@Styles.Render("~/Content/KinderEditor")
@Scripts.Render("~/bundles/KinderEditor")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowApply</title>
    <script type="text/javascript">
        $(function () {
            var userId = $("#userId").text();
            $("#Applyer").val(userId);
            $("#IsAuthenticated").css("display", "none");
            bindFileUpload();
            //alert(userId);
        });
        KindEditor.ready(function (K) {
            var editor1 = K.create('#MsgContent', {
                cssPath: '/KinderEditor/plugins/code/prettify.css',
                uploadJson: '/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson: '/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterBlur: function () { this.sync(); },//注意这里（异步提交时需要同步）
                afterCreate: function () {
                    var self = this;
                    self.sync();//把富文本编辑器的内容放到  文本域里面去。

                }
            });
            prettyPrint();//注意要调用该方法.
        });
        function bindFileUpload() {

            $("#btnFileUp").click(function () {
                if ($("#imgIcon").val() == "") {
                    $.messager.alert("提示", "请选择文件");
                    return;
                }
                //alert("bindFileUpload");
                $("#addForm").ajaxSubmit({
                    type: 'post',
                    url: '/Meet/FileUpload',
                    success: function (data) {
                        //alert("success");
                        var serverData = data.split(':');
                        if (serverData[0] == "ok") {
                            //alert(serverData[1]);
                            $("#fileUpImage").attr("value", serverData[1]);//将服务端返回的图片路径赋给隐藏域
                            $("#showImage").append("<span>上传成功</span>");
                        } else {
                            $.messager.alert("提示", "文件上传错误!");
                        }
                    }
                });
            });
            return false;
        }
        //提交表单
        function SubForm() {
            $("#addForm").submit();
        }
        function afterAddRoom(data) {
            window.parent.afterAddRoom(data);
        }
    </script>
    <style>
        img{
            width:100px;
        }
    </style>
</head>
<body>
    <div id="IsAuthenticated">
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink(User.Identity.GetUserId(), null, null, routeValues: null, htmlAttributes: new { title = "管理", id = "userId" })
        }
    </div>
    <div>
        @using (Ajax.BeginForm("Add", "MeetRoom", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAddRoom" }, new { id = "addForm", enctype = "multipart/form-data" }))
        {
            if (ViewData["meetRoom"] == null)
            {
                <table>
                    <tr><td>会议室名</td><td><input type="text" name="Name" /></td></tr>
                    <tr><td>容纳人数</td><td><input type="text" name="HoldPerson" /></td></tr>
                    <tr><td>会议室地址</td><td><input type="text" name="Address" /></td></tr>
                    <tr>
                        <td>上传图片</td>
                        <td>
                            <input type="file" name="fileUp" id="imgIcon" />
                            <input type="button" value="上传图片" id="btnFileUp" />
                            <input type="hidden" id="fileUpImage" name="Picture" />
                            <div id="showImage">
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>描述</td>
                        <td>
                            <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Describe"></textarea>
                        </td>

                    </tr>
                </table>
            }
            else
            {
                <table>
                    <tr><td>会议室名字</td><td><input type="text" name="Name" value="@ViewData["Name"]" /></td></tr>
                    <tr><td>容纳人数</td><td><input type="text" name="HoldPerson" value="@ViewData["HoldPerson"]" /></td></tr>
                    <tr><td>会议室地址</td><td><input type="text" name="Address" value="@ViewData["Address"]" /></td></tr>
                    <tr>
                        <td>上传图片</td>
                        <td>

                            <input type="hidden" id="MeetRoomId" name="MeetRoomId" value="@ViewData["MeetRoomId"]" />
                            <input type="file" name="fileUp" id="imgIcon" />
                            <input type="button" value="上传图片" id="btnFileUp" />
                            <div id="showImage">
                                @if (ViewData["Picture"]!=null && !String.IsNullOrEmpty(ViewData["Picture"].ToString()))
                                {
                                    <img src="@ViewData["Picture"]" />
                                <input type="hidden" id="fileUpImage" name="Picture" value="@ViewData["Picture"]"/>
                                }
                                else
                                {
                                    <input type="hidden" id="fileUpImage" name="Picture" disabled />
                                }
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>描述</td>
                        <td>
                            @{
                                string str = @ViewData["Describe"].ToString();
                                MvcHtmlString html = new MvcHtmlString(str);
                            }
                            @*<p>@MvcHtmlString.Create(@ViewData["Describe"].ToString())</p>*@
                            <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Describe">@html</textarea>
                           
                        </td>

                    </tr>
                </table>
            }

        }
    </div>
</body>
</html>

WebApp/Views/MeetRoom/Index.cshtml
@{
    Layout = null;
}
@using Model
@using Common
@using Microsoft.AspNet.Identity
@Styles.Render("~/Content/table")
@Styles.Render("~/Content/easyui")
@Scripts.Render("~/bundles/easyui")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MeetRoom</title>
    <script type="text/javascript">

        $(function () {
            $(".addDiv").css("display", "none");
            $(".addInfo").click(function () {
                //alert("addInfo");
                addInfo();
            });
            $(".detailDiv").css("display", "none");
            $(".detail").click(function () {
                showDetail($(this).attr("ids"));
            });

            $(".delete").click(function () {
                deleteInfo($(this).attr("ids"), $(this));
            });
            $(".update").click(function () {
                updateInfo($(this).attr("ids"));
            });
            var userId = $("#userId").text();
            $("#ApplyPeople").val(userId);
            $("#IsAuthenticated").css("display", "none");
        });

        function addInfo() {
            $("#addFrame").attr("src", "/MeetRoom/AddMeetRoom");
            $(".addDiv").css("display", "block");
            $(".addDiv").dialog({
                modal: true,
                resizable: true,
                maximizable: true,
                collapsiable: true,
                title: "会议室添加",
                width: 700,
                height: 400,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //调用子窗体中的方法
                        var childWindow = $("#addFrame")[0].contentWindow;
                        childWindow.SubForm();
                    }
                }, {
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        $('.addDiv').dialog("close", true);
                    }
                }]
            });
        }

        function updateInfo(id) {
            $("#addFrame").attr("src", "/MeetRoom/AddMeetRoom?id="+id);
            $(".addDiv").css("display", "block");
            $(".addDiv").dialog({
                modal: true,
                resizable: true,
                maximizable: true,
                collapsiable: true,
                title: "会议室更新",
                width: 700,
                height: 400,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //调用子窗体中的方法
                        var childWindow = $("#addFrame")[0].contentWindow;
                        childWindow.SubForm();
                    }
                }, {
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        $('.addDiv').dialog("close", true);
                    }
                }]
            });
        }

        //添加完成以后执行该方法
        function afterAddRoom(serverData) {
            $('.addDiv').dialog('close', true);
            $.messager.show({
                title: '提示',
                msg: '添加成功',
                showType: 'show'
            });
            location.reload();
        }

        function deleteInfo(id, control) {
            $.messager.confirm("提示", "确定要删除该会议室吗？", function (r) {
                if (r) {
                    //删除
                    $.post("/MeetRoom/Delete", { "id": id }, function (data) {
                        if (data == "ok") {
                            $(control).parent().parent().remove();
                            $.messager.show({
                                title: '提示',
                                msg: '删除成功',
                                showType: 'show'
                            });
                        } else {
                            $.messager.alert("提示", "删除失败", "info");
                        }
                    });

                } else {

                }
            });
        }

        function showDetail(id) {
            $.post("/MeetRoom/MeetRoomDetail", { "id": id }, function (data) {
                $("#Name").text("");
                $("#HoldPerson").text("");
                $("#Address").text("");
                $("#Status").text("");
                $("#Picture").attr("src","");
                $("#Describe").html("");


                $("#Name").text(data.Name);
                $("#HoldPerson").text(data.HoldPerson);
                $("#Address").text(data.Address);
                $("#Describe").html(data.Describe);
                
                $("#Status").text(data.Status == 0 ? "未使用" : (data.Status == 1 ? "已预约" : "已使用"));
                $("#Picture").attr("src", data.Picture);
            });
            $(".detailDiv").css("display", "block");
            $(".detailDiv").dialog({
                modal: true,
                resizable: true,
                maximizable: true,
                collapsiable: true,
                title: "会议室详情",
                width: 700,
                height: 350,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        $('.detailDiv').dialog("close", true);
                    }
                }]
            }
           );
        }

        //将序列化成json格式后日期(毫秒数)转成日期格式
        function ChangeDateFormat(cellval) {
            var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));
            var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
            var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
            return date.getFullYear() + "-" + month + "-" + currentDate;
        }

    </script>
</head>
<body>
    <div id="IsAuthenticated">
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink(User.Identity.GetUserId(), null, null, routeValues: null, htmlAttributes: new { title = "管理", id = "userId" })
        }
    </div>
    <div>
        @using (Html.BeginForm())
        {
            <p>
                @*type:@Html.DropDownList("meetType","All")*@
                Title or Content:@Html.TextBox("searchString")<br />
                @*Title or Content:<input type="text" value="@ViewData["searchString"]" />*@
                <input type="submit" value="搜索" />
            </p>
        }
    </div>
    <div>
        <a href="#" class="addInfo">会议室添加</a><br /><br />
        <div style="font-size:large">会议室管理</div><br /><br />
        @if (ViewData["meetRooms"] == null || ((List<MeetRoom>)ViewData["meetRooms"]).Count == 0)
        {
            <p>暂无任何会议室，去添加一个吧</p>
        }
        else
        {
            <div>
                <table width="100%">
                    <tr>
                        <th>会议室名</th>
                        <th>容纳人数</th>
                        <th>会议室地址</th>
                        <th>状态</th>
                        <th>详细</th>
                        <th>删除</th>
                        <th>更新</th>
                    </tr>
                    @foreach (MeetRoom m in (List<MeetRoom>)ViewData["meetRooms"])
                    {
                        <tr>
                            <td>@m.Name</td>
                            <td>@m.HoldPerson</td>
                            <td>@m.Address</td>
                            @if (m.Status == 0)
                            {
                                <td>未使用</td>
                            }
                            else if (m.Status == 1)
                            {
                                <td>已预约</td>
                            }
                            else if (m.Status == 2)
                            {
                                <td>未预约</td>
                            }
                            <td><a href="#" class="detail" ids="@m.MeetRoomId">详细</a></td>
                            <td><a href="#" class="delete" ids="@m.MeetRoomId">删除</a></td>
                            <td><a href="#" class="update" ids="@m.MeetRoomId">更新</a></td>

                        </tr>
                    }
                </table>
                <p class="page_nav">
                    @MvcHtmlString.Create(PageBar.GetPageBar((int)ViewData["pageIndex"], (int)ViewData["pageCount"]))
                </p>
            </div>
        }

    </div>

    <!--显示详细内容--->
    <div class="detailDiv" style="overflow:scroll;">
        <table>
            <tr><td>会议室名</td><td><span id="Name"></span></td></tr>
            <tr><td>容纳人数</td><td><span id="HoldPerson"></span></td></tr>
            <tr><td>会议室地址</td><td><span id="Address"></span></td></tr>
            <tr><td>状态</td><td><span id="Status"></span></td></tr>
            <tr><td>描述</td><td><span id="Describe"></span></td></tr>
            <tr><td>图片</td><td><img id="Picture" /></td>
        </table>
    </div>
    <!--显示详细内容结束--->
    <!--添加内容--->
    <div class="addDiv" style="overflow:hidden;">
        <iframe id="addFrame" frameborder="0" width="100%" height="100%" scrolling="auto" src="" />
    </div>
    <!--添加内容结束--->

</body>
</html>