WebApp/Controllers/MeetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using BLL;
using System.IO;

namespace WebApp.Controllers
{
    [Authorize]
    public class MeetController : Controller
    {
        private IMeetService meetService = BLLContainer.Resolve<IMeetService>();
        private IExamineService examineService = BLLContainer.Resolve<IExamineService>();
        private IMeetMsgService meetMsgService = BLLContainer.Resolve<IMeetMsgService>();
        private IMeetRoomService meetRoomService = BLLContainer.Resolve<IMeetRoomService>();
        //
        // GET: /Meet/

        //0:未审核 1：审核通过 -1：审核未通过 2：纪要 3：归档失败 4：归档成功

        //删除时更改Status
        //meetmemo 内容加载不起
        //meet Status审核和纪要可以同时共存

        //传pageIndex 和传ID 冲突 在meetApply meetExamine等，只有有pageBar全有冲突

        //申请者的申请审核后无法修改删除 纪要者的纪要归档后无法修改删除

        //各单位的更新问题？？？

        //查询等冗余代码封装问题？？

        //显示加载 不能使用延迟加载 meet 指明meetMsg  不然update后置空   有问题 要是本身没有Examine等怎么加载
        //Meet updateMeet = meetService.GetModels(p => p.MeetId == meet.MeetId && p.Examine.ExamineId == meet.MeetId && p.MeetMsg.MeetMsgId == meet.MeetId).FirstOrDefault();
        //显示加载
            //if (meet.MeetMsg != null)
            //{
            //    int mid = meet.MeetMsg.MeetMsgId;
            //}
            //if (meet.Examine != null)
            //{
            //    int eid = meet.Examine.ExamineId;
            //}      

        //靠Status支持的太脆弱，判断Examine是否存在

        //easyui子界面如会议通知，登录，发现不能刷新全界面，在login.cshtml中把Html.BeginForm改成Ajax.BeginForm(引入js)
        //然后写一个回调函数，回调父界面的刷新界面函数，不能直接用子界面的刷新，只会刷新子界面

        //实现搜索 没有实现类型搜索
        //搜索会搜索到HTML标签中的内容，如何避免？？？？搜t会搜到<strong>的t



        #region 会议申请
        [Authorize(Roles = "apply,admin")]
        public ActionResult MeetManager()
        {
            //string id = Request.Params["id"];
            //List<Meet> meets = meetService.GetModels(p => p.ApplyPeople==id).ToList();
            //ViewData["meets"] = meets;
            string id = Request.Params["id"];
            int pageSize = 5;
            int itemCount = meetService.GetModels(p => p.ApplyPeople == id).Count();
            int pageCount = Convert.ToInt32(Math.Ceiling((double)itemCount / pageSize));
            //当前页码值
            int pageIndex = Request.Params["pageIndex"] == null ? 1 : int.Parse(Request.Params["pageIndex"]);
            pageIndex = pageIndex > pageCount ? pageCount : pageIndex;
            List<Meet> meets = null;
            if (itemCount != 0 && pageIndex != 0)
            {
                meets = meetService.GetModelsByPage<Nullable<DateTime>>(pageSize, pageIndex, true, a => a.StartTime, p => p.ApplyPeople == id).ToList();

            }
            ViewData["meets"] = meets;
            ViewData["pageCount"] = pageCount;
            ViewData["pageIndex"] = pageIndex;
            if (Request.Params["id"] != null)
            {
                ViewData["id"] = id;
            }
            return View();
        }
        [Authorize(Roles = "apply,admin")]
        public ActionResult ApplyedMeet()
        {
            int id = int.Parse(Request.Params["id"]);
            MeetRoom meetRoom = meetRoomService.GetModels(p=>p.MeetRoomId==id).FirstOrDefault();
            List<Meet> meets = new List<Meet>();
            String[] dates = new String[0];
            if (meetRoom!=null && !String.IsNullOrEmpty(meetRoom.UseTime))
            {
               dates = meetRoom.UseTime.Split('|');
            }
            foreach (String date in dates)
            {
                String[] startend = date.Split(',');
                int mid = int.Parse(startend[0]);
                Meet meet = meetService.GetModels(p => p.MeetId == mid).FirstOrDefault();
                meets.Add(meet);
            }
            ViewData["meets"] = meets;
            return View();
        }
        [Authorize(Roles = "apply,admin")]

        public ActionResult MeetApply(string searchString)
        {
            int pageSize = 5;
            int itemCount;
            if (!String.IsNullOrEmpty(searchString))
            {
                itemCount = meetRoomService.GetModels(p => p.Name.Contains(searchString) || p.Content.Contains(searchString)).Count();
            }
            else
            {
                itemCount = meetRoomService.GetModels(p => true).Count();
            }
            int pageCount = Convert.ToInt32(Math.Ceiling((double)itemCount / pageSize));
            //当前页码值
            int pageIndex = Request.Params["pageIndex"] == null ? 1 : int.Parse(Request.Params["pageIndex"]);
            pageIndex = pageIndex > pageCount ? pageCount : pageIndex;
            List<MeetRoom> meetRooms = null;
            if (itemCount != 0 && pageIndex != 0)
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    meetRooms = meetRoomService.GetModelsByPage(pageSize, pageIndex, true, a => a.Name, p => p.Name.Contains(searchString) || p.Content.Contains(searchString)).ToList();
                }
                else
                {
                    meetRooms = meetRoomService.GetModelsByPage(pageSize, pageIndex, true, a => a.Name, p => true).ToList();
                }
            }
            ViewData["meetRooms"] = meetRooms;
            ViewData["pageCount"] = pageCount;
            ViewData["pageIndex"] = pageIndex;
            ViewData["searchString"] = searchString;
            return View();
            return View();
        }
        [Authorize(Roles = "apply,admin")]
        public ActionResult ShowApply()
        {
            if (Request.Params["id"] != null)
            {
                int id = int.Parse(Request.Params["id"]);
                Meet meet = meetService.GetModels(p=>p.MeetId==id).FirstOrDefault();
                ViewData["meet"] = meet;
                ViewData["Title"] = meet.Title;
                ViewData["Type"] = meet.Type;
                ViewData["HostPeople"] = meet.HostPeople;
                ViewData["Budget"] = meet.Budget;
                ViewData["Address"] = meet.Address;
                ViewData["StartTime"] = meet.StartTime;
                ViewData["EndTime"] = meet.EndTime;
                ViewData["Content"] = meet.Content;
                ViewData["ApplyPeople"] = meet.ApplyPeople;
                ViewData["MeetId"] = meet.MeetId;
                ViewData["Other"] = meet.Other;
            }
            return View();
        }
        [Authorize(Roles = "apply,admin")]
        [ValidateInput(false)]
        public ActionResult Apply(Meet meet)
        {

           // DateTime d =  DateTime.Parse("1997-10-12 11:10:12");
            //String de = d.ToShortDateString();
            //try
            //{
            //    if(meet.StartTime!=null)
            //        DateTime.Parse(meet.StartTime.ToString());
            //    if (meet.EndTime != null)
            //        DateTime.Parse(meet.EndTime.ToString());
            //}catch(Exception e){
            //    return Content("no:时间格式不对");
            //}
            DateTime d = DateTime.Parse("0001-1-1 0:0:0");
            if (meet.StartTime==null || meet.StartTime == d)
            {
                return Content("no:开始时间不能为空或格式不对");
            }
            else
            {
                if (DateTime.Compare(DateTime.Parse(meet.StartTime.ToString()), DateTime.Now) < 0)
                {
                    return Content("no:开始时间不能为过去时间");
                }
            }
            if (meet.EndTime == null || meet.EndTime == d)
            {
                return Content("no:结束时间不能为空或格式不对");
            }
            else
            {
                if (DateTime.Compare(DateTime.Parse(meet.EndTime.ToString()), DateTime.Now) < 0)
                {
                    return Content("no:结束时间不能为过去时间");
                }
                if (meet.StartTime!=null && DateTime.Compare(DateTime.Parse(meet.EndTime.ToString()), DateTime.Parse(meet.StartTime.ToString())) < 0)
                {
                    return Content("no:结束时间不能小于开始时间");
                }
            }



            //0申请
            meet.Status = 0;
            int mid = int.Parse(meet.Other);
            MeetRoom meetRoom = meetRoomService.GetModels(p => p.MeetRoomId == mid).FirstOrDefault();

            //显示加载
            Meet updateMeet = meetService.GetModels(p => p.MeetId == meet.MeetId).FirstOrDefault();
            String[] dates = new String[0];
            if (!String.IsNullOrEmpty(meetRoom.UseTime))
            {
               dates = meetRoom.UseTime.Split('|');
            }
            String str = "";
            bool isOk = true;
            foreach (String date in dates)
            {
                String[] startend = date.Split(',');
                if (updateMeet != null && startend[0]==updateMeet.MeetId.ToString())
                {
                    //是更改时间,移去更改的时间
                }
                else{
                    if (DateTime.Compare(DateTime.Now, DateTime.Parse(startend[2])) > 0)
                    {
                        //移去 时间过了
                    }
                    else
                    {

                        if (String.IsNullOrEmpty(str))
                        {
                            str += date;
                        }
                        else
                        {
                            str += "|" + date;

                        }
                        bool b1 = DateTime.Compare(DateTime.Parse(meet.StartTime.ToString()), DateTime.Parse(startend[1])) >= 0;
                        bool b2 = DateTime.Compare(DateTime.Parse(meet.StartTime.ToString()), DateTime.Parse(startend[2])) <= 0;
                        bool b3 = DateTime.Compare(DateTime.Parse(meet.EndTime.ToString()), DateTime.Parse(startend[1])) >= 0;
                        bool b4 = DateTime.Compare(DateTime.Parse(meet.EndTime.ToString()), DateTime.Parse(startend[2])) <= 0;

WebApp/Views/Meet/ShowApply.cshtml

@{
    Layout = null;
}
@using Microsoft.AspNet.Identity
@using System.Web.Security
@Styles.Render("~/Content/table")
@Styles.Render("~/Content/easyui")
@Scripts.Render("~/bundles/easyui")
@Styles.Render("~/Content/date")
@Scripts.Render("~/bundles/date")
@Scripts.Render("~/bundles/ajax")
@Styles.Render("~/Content/KinderEditor")
@Scripts.Render("~/bundles/KinderEditor")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> 
    <title>ShowApply</title>
    <script type="text/javascript">
        $(function () {
            var userId = $("#userId").text();
            $("#Applyer").val(userId);
            $("#IsAuthenticated").css("display", "none");
            bindFileUpload();
            $('.input_cxcalendar').each(function () {
                var a = new Calendar({
                    targetCls: $(this),
                    type: 'yyyy-mm-dd HH:MM:SS',
                    wday: 2
                }, function (val) {
                    console.log(val);
                });
            });
            //alert(userId);
        });
        KindEditor.ready(function (K) {
            var editor1 = K.create('#MsgContent', {
                cssPath: '/KinderEditor/plugins/code/prettify.css',
                uploadJson: '/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson: '/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterBlur: function () { this.sync(); },//注意这里（异步提交时需要同步）
                afterCreate: function () {
                    var self = this;
                    self.sync();//把富文本编辑器的内容放到  文本域里面去。

                }
            });
            prettyPrint();//注意要调用该方法.
        });
        function bindFileUpload() {
        
            $("#btnFileUp").click(function () {
                if ($("#imgIcon").val() == "") {
                    $.messager.alert("提示", "请选择文件");
                    return;
                }
                //alert("bindFileUpload");
                $("#addForm").ajaxSubmit({
                    type: 'post',
                    url: '/Meet/FileUpload',
                    success: function (data) {
                        //alert("success");
                        var serverData = data.split(':');
                        if (serverData[0] == "ok") {
                            //alert(serverData[1]);
                            $("#fileUpImage").attr("value", serverData[1]);//将服务端返回的图片路径赋给隐藏域
                            $("#showImage").append("<span>上传成功</span>");
                        } else {
                            $.messager.alert("提示", "文件上传错误!");
                        }
                    }
                });
            });
            return false;
        }
        //提交表单
        function SubForm(id) {
            //alert("meetRoom:" + id);
            $("#Other").val(id);
            $("#addForm").submit();
        }
        function afterApply(data) {
            window.parent.afterApply(data);
        }
    </script>
</head>
<body>
    <div id="IsAuthenticated">
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink(User.Identity.GetUserId(), null, null, routeValues: null, htmlAttributes: new { title = "管理", id = "userId" })
        }
    </div>
    <div> 
        @using (Ajax.BeginForm("Apply", "Meet", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterApply", OnComplete = "afterApply", OnFailure = "afterApply" }, new { id = "addForm", enctype = "multipart/form-data" }))
        {
            if (ViewData["meet"] == null)
            {
                <table>
                <tr><td>会议标题</td><td><input type="text" name="Title" /></td></tr>
                <tr><td>会议类型</td><td><input type="text" name="Type" /></td></tr>
                <tr><td>主持人</td><td><input type="text" name="HostPeople" /></td></tr>
                <tr><td>预算</td><td><input type="text" name="Budget" /></td></tr>
                <tr><td>地址</td><td><input type="text" name="Address" /></td></tr>
                <tr><td>开始时间</td><td><input type="text" name="StartTime" class="input_cxcalendar" style="width:200px;" /></td></tr>
                <tr><td>结束时间</td><td><input type="text" name="EndTime" class="input_cxcalendar" style="width:200px;" /></td></tr>
                <tr>
                    <td>上传附件</td>
                    <td>
                        <input type="file" name="fileUp" id="imgIcon" />
                        <input type="button" value="上传附件" id="btnFileUp" />
                        <input type="hidden" id="fileUpImage" name="File" />
                        <input type="hidden" id="Applyer" name="ApplyPeople" />
                        <div id="showImage">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>内容</td>
                    <td>
                        <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Content"></textarea>
                        <input type="hidden" id="Other" name="Other" />
                    </td>

                </tr>
            </table>
            }
            else
            {
                <table>
                <tr><td>会议标题</td><td><input type="text" name="Title"  value="@ViewData["Title"]" /></td></tr>
                <tr><td>会议类型</td><td><input type="text" name="Type" value="@ViewData["Type"]" /></td></tr>
                <tr><td>主持人</td><td><input type="text" name="HostPeople" value="@ViewData["HostPeople"]" /></td></tr>
                <tr><td>预算</td><td><input type="text" name="Budget" value="@ViewData["Budget"]" /></td></tr>
                <tr><td>地址</td><td><input type="text" name="Address" value="@ViewData["Address"]" /></td></tr>
                <tr><td>开始时间</td><td><input type="text" name="StartTime" value="@ViewData["StartTime"]" /></td></tr>
                <tr><td>结束时间</td><td><input type="text" name="EndTime" value="@ViewData["EndTime"]" /></td></tr>
                <tr>
                    <td>内容</td>
                    <td>
                        <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Content" >@ViewData["Content"]</textarea>
                        <input type="hidden" id="MeetId" name="MeetId" value="@ViewData["MeetId"].ToString()" />
                        <input type="hidden" id="ApplyPeople" name="ApplyPeople" value="@ViewData["ApplyPeople"]" />
                        <input type="hidden" name="Other" value="@ViewData["Other"]" />
                    </td>
                </tr>
            </table>
            }
            
        }
    </div>
</body>
</html>

WebApp/Views/Meet/ShowExamine.cshtml
@{
    Layout = null;
}
@using Model
@using Microsoft.AspNet.Identity
@using System.Web.Security
@Styles.Render("~/Content/table")
@Styles.Render("~/Content/easyui")
@Scripts.Render("~/bundles/easyui")
@Scripts.Render("~/bundles/ajax")
@Styles.Render("~/Content/KinderEditor")
@Scripts.Render("~/bundles/KinderEditor")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowApply</title>
    <script type="text/javascript">
        $(function () {
            var userId = $("#userId").text();
            $("#ExaminePeople").val(userId);
            $("#IsAuthenticated").css("display", "none");
            bindClick();
            
        });
        KindEditor.ready(function (K) {
            var editor1 = K.create('#MsgContent', {
                cssPath: '/KinderEditor/plugins/code/prettify.css',
                uploadJson: '/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson: '/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterBlur: function () { this.sync(); },//注意这里（异步提交时需要同步）
                afterCreate: function () {
                    var self = this;
                    self.sync();//把富文本编辑器的内容放到  文本域里面去。

                }
            });
            var editor1 = K.create('#ExaContent', {
                cssPath: '/KinderEditor/plugins/code/prettify.css',
                uploadJson: '/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson: '/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterBlur: function () { this.sync(); },//注意这里（异步提交时需要同步）
                afterCreate: function () {
                    var self = this;
                    self.sync();//把富文本编辑器的内容放到  文本域里面去。

                }
            });
            prettyPrint();//注意要调用该方法.
        });
        //提交表单
        function SubForm() {
            $("#examineForm").submit();
        }
        function afterExamine(data) {
            window.parent.afterExamine(data);
        }
        function bindClick() {
            $(".examineno").click(function () {
                //alert("examineno");
                $("#Status").val(-1);
            });
        }
    </script>
</head>
<body>
    <div id="IsAuthenticated">
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink(User.Identity.GetUserId(), null, null, routeValues: null, htmlAttributes: new { title = "管理", id = "userId" })
        }
    </div>
    <div>
        @*@if (m = ViewData["meet"] != null){*@
            @using (Ajax.BeginForm("Examine", "Meet", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterExamine" }, new { id = "examineForm", enctype = "multipart/form-data" }))
            {
                <table>
                <tr><td>会议标题</td><td><input type="text" name="Title" disabled="true" value="@ViewData["Title"]" /></td></tr>
                <tr><td>会议类型</td><td><input type="text" name="Type" disabled="true" value="@ViewData["Type"]" /></td></tr>
                <tr><td>主持人</td><td><input type="text" name="HostPeople" disabled="true" value="@ViewData["HostPeople"]" /></td></tr>
                <tr><td>预算</td><td><input type="text" name="Budget" disabled="true" value="@ViewData["Budget"]" /></td></tr>
                <tr><td>地址</td><td><input type="text" name="Address" disabled="true" value="@ViewData["Address"]" /></td></tr>
                <tr><td>开始时间</td><td><input type="text" name="StartTime" disabled="true" value="@ViewData["StartTime"]" /></td></tr>
                <tr><td>结束时间</td><td><input type="text" name="EndTime" disabled="true" value="@ViewData["EndTime"]" /></td></tr>
                <tr>
                    <td>内容</td>
                    <td>
                        <textarea disabled="true" id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="c">"@ViewData["Content"]</textarea>
                    </td>

                </tr>
                    <tr>
                    <tr><td>审核通过</td>
                    <td>
                        <input type="radio" class="examineok" name="radio" value="1" checked />审核通过
                        <input type="radio" class="examineno" name="radio" value="-1" />审核未通过
                        <input type="hidden" id="Status" name="Roles" value="1" />
                    </td></tr>
                    <td>审核内容</td>
                    <td>
                        <textarea id="ExaContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Content"></textarea>
                    </td>
                    <input type="hidden" id="ExaminePeople" name="ExaminePeople" />
                    
                    <input type="hidden" id="MeetId" name="Other" value="@ViewData["id"]" />
                </tr>
            </table>
            }
        @*}
        else
        {
            <span>出现问题了</span>
        }*@
    </div>
</body>
</html>

WebApp/Views/Meet/ShowMemo.cshtml
@{
    Layout = null;
}
@using Model
@using Microsoft.AspNet.Identity
@using System.Web.Security
@Styles.Render("~/Content/table")
@Styles.Render("~/Content/easyui")
@Scripts.Render("~/bundles/easyui")
@Scripts.Render("~/bundles/ajax")
@Styles.Render("~/Content/KinderEditor")
@Scripts.Render("~/bundles/KinderEditor")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowApply</title>
    <script type="text/javascript">
        $(function () {
            var userId = $("#userId").text();
            $("#Recorder").val(userId);
            $("#IsAuthenticated").css("display", "none");
            bindClick();

        });
        KindEditor.ready(function (K) {
            var editor1 = K.create('#MsgContent', {
                cssPath: '/KinderEditor/plugins/code/prettify.css',
                uploadJson: '/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson: '/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterBlur: function () { this.sync(); },//注意这里（异步提交时需要同步）
                afterCreate: function () {
                    var self = this;
                    self.sync();//把富文本编辑器的内容放到  文本域里面去。

                }
            });
            prettyPrint();//注意要调用该方法.
        });
        //提交表单
        function SubForm() {
            $("#memoForm").submit();
        }
        function afterMemo(data) {
            window.parent.afterMemo(data);
        }
    </script>
</head>
<body>
    <div id="IsAuthenticated">
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink(User.Identity.GetUserId(), null, null, routeValues: null, htmlAttributes: new { title = "管理", id = "userId" })
        }
    </div>
    <div>
        @using (Ajax.BeginForm("Memo", "Meet", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterMemo" }, new { id = "memoForm", enctype = "multipart/form-data" }))
        {
            if (ViewData["meetMsg"] == null)
            {
                <table>
                    <tr><td>纪要标题</td><td><input type="text" name="Name" /></td></tr>
                    <tr>
                        <td>纪要内容</td>
                        <td>
                            <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Content"></textarea>
                            <input type="hidden" id="Recorder" name="Recorder" />
                            <input type="hidden" id="MeetId" name="Other" value="@ViewData["id"]" />
                            <input type="hidden" id="MeetMsgId" name="MeetMsgId" value="@ViewData["MeetMsgId"]" />
                        </td>
                    </tr>
                </table>
            }
            else
            {
                <table>
                    <tr><td>纪要标题</td><td><input type="text" name="Name" value="@ViewData["Name"]" /></td></tr>
                    <tr>
                        <td>纪要内容</td>
                        <td>
                            <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height: 200px; " name="Content">@ViewData["Content"]</textarea>
                            <input type="hidden" id="Recorder" name="Recorder" />
                            <input type="hidden" id="MeetId" name="Other" value="@ViewData["id"]" />
                            <input type="hidden" id="MeetMsgId" name="MeetMsgId" value="@ViewData["MeetMsgId"]" />
                        </td>
                    </tr>
                </table>
            }
        }
    </div>
</body>
</html>